# .air.toml
[build]
cmd = "go build -o ./tmp/gostart ./cmd/gostart"
bin = "tmp/gostart"
include_ext = ["go", "tpl", "tmpl"]
delay = 500
stop_on_error = true

[watch]
includes = ["."]
excludes = ["tmp"]

[log]
level = "debug"

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
clean_on_exit = true

[screen]
clear_on_rebuild = false
keep_scroll = true
